// app/api/documents/[id]/download/route.ts
// Real export in any format the customer needs - text, DOCX, or PDF - all
// generated server-side from the actual stored document content, not a
// "Download DOCX" button that silently does nothing.
// CR AudioViz AI · EIN 39-3646201 · July 30, 2026
import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { Document, Packer, Paragraph } from "docx";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const dynamic = "force-dynamic";

const SB_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SB_SVC = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";

export async function GET(req: NextRequest, { params }: { params: { id: string } }): Promise<NextResponse> {
  if (!SB_URL || !SB_SVC) return NextResponse.json({ error: "Service unavailable" }, { status: 503 });
  const sb = createClient(SB_URL, SB_SVC, { auth: { persistSession: false } });

  const h = req.headers.get("authorization");
  const token = h?.startsWith("Bearer ") ? h.slice(7) : null;
  if (!token) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { data: { user } } = await sb.auth.getUser(token);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: doc } = await sb.from("legalease_documents")
    .select("*").eq("id", params.id).eq("user_id", user.id).maybeSingle();
  if (!doc) return NextResponse.json({ error: "Document not found" }, { status: 404 });

  const format = req.nextUrl.searchParams.get("format") ?? "txt";
  const disclaimer = (doc.metadata as { disclaimer?: string })?.disclaimer
    ?? "This document was generated by AI and is not legal advice. Have a licensed attorney review it before you rely on it.";
  const fullText = `${doc.content}\n\n---\n${disclaimer}`;
  const safeName = (doc.title as string).replace(/[^a-z0-9]+/gi, "-").toLowerCase();

  if (format === "txt") {
    return new NextResponse(fullText, {
      headers: { "Content-Type": "text/plain", "Content-Disposition": `attachment; filename="${safeName}.txt"` },
    });
  }

  if (format === "docx") {
    const docx = new Document({
      sections: [{
        children: fullText.split("\n").map(line => new Paragraph({ text: line })),
      }],
    });
    const buffer = await Packer.toBuffer(docx);
    return new NextResponse(buffer, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${safeName}.docx"`,
      },
    });
  }

  if (format === "pdf") {
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontSize = 11;
    const margin = 50;
    const pageWidth = 612, pageHeight = 792;
    const maxWidth = pageWidth - margin * 2;

    // Word-wrap manually - pdf-lib has no built-in text flow.
    const words = fullText.split(/\s+/);
    let page = pdfDoc.addPage([pageWidth, pageHeight]);
    let y = pageHeight - margin;
    let line = "";
    for (const word of words) {
      const testLine = line ? `${line} ${word}` : word;
      const width = font.widthOfTextAtSize(testLine, fontSize);
      if (width > maxWidth) {
        page.drawText(line, { x: margin, y, size: fontSize, font, color: rgb(0, 0, 0) });
        y -= fontSize + 4;
        line = word;
        if (y < margin) { page = pdfDoc.addPage([pageWidth, pageHeight]); y = pageHeight - margin; }
      } else {
        line = testLine;
      }
    }
    if (line) page.drawText(line, { x: margin, y, size: fontSize, font, color: rgb(0, 0, 0) });

    const pdfBytes = await pdfDoc.save();
    return new NextResponse(Buffer.from(pdfBytes), {
      headers: { "Content-Type": "application/pdf", "Content-Disposition": `attachment; filename="${safeName}.pdf"` },
    });
  }

  return NextResponse.json({ error: "Unsupported format - use txt, docx, or pdf" }, { status: 400 });
}
